Ex3 js objects part1
MichaelMindman/external-courses pull request #3
Opened 2022-03-15 10:05 UTC by MichaelMindman

Добрый день Павел!
Задания из Ex3.
Сделаны 6/7 task, попробую сделать 7 task, если успею за сегодня.
Первые 1-5 task выполнены, пройдены все тесты.
6 task: пройден npm test, линтер выводит две ошибки, которые пришлось отключить:

0шибка-1 
error  'objectInput' is already declared in the upper scope on line 1 column 22                                                                                               no-shadow
Поизучал её (освоил её, потратил час), но не совсем понимаю что можно улучшить, что бы код выполнялся и работал без дополнительных объёмов кода.

ошибка-2 
error  for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array  no-restricted-syntax
Говорит о том чтобы из кода убрать цикл For - для более "лучшего синтаксиса". Но его я использую два раза: для рекурсии и прохождения по цепочке ключ-значение в объекте. И еще при "удалении" из строчки с ключами -"точек". То есть For используется, убирать его не могу.

ПС.
Задания интересные и немного сложные для новичка!
Всего неделю назад для меня понятие Объект был чем-то тождественным сj ...  cловарем из Python. А теперь это какая вездесущая сущность, которая берет начало от null.

2022-03-15 11:06 UTC, spiderpoul commented on src/ex3_js-objects-part1/task-06.js
> +    return String(resultValue);
а для чего возвращаемое значение конвертировать в строку?

2022-03-15 11:11 UTC, spiderpoul commented on src/ex3_js-objects-part1/task-06.js
> +          getCheckObject(objectInput[key]);
довольно как-то всё усложнено, попробуй упростить алгоритм. Тебе нужно получить массив пути с ключами (`Object.keys(propertyPath.split('.'))`) и по нему в цикле идти по пути объекта `value = value[key]`
но тут нужно делать проверку на то, есть ли ключ или нет, если его нет, то сразу возвращаем `undefined`и цикл останавливается.

2022-03-15 11:37 UTC, MichaelMindman commented on src/ex3_js-objects-part1/task-06.js
> +    return String(resultValue);
По тесту финальный результат - это значение последнего ключа (объекта), и он сравнивается в виде строки   'awf'.
 resultValue выводится в виде [awr], 
Поэтому помещаю resultValue в обертку String.

2022-03-15 11:38 UTC, MichaelMindman commented on src/ex3_js-objects-part1/task-06.js
> +          getCheckObject(objectInput[key]);
Постараюсь!!!!

2022-03-15 11:39 UTC, spiderpoul commented on src/ex3_js-objects-part1/task-06.js
> +    return String(resultValue);
в реальности это может быть что угодно, число, строка, объект и даже функция. Конвертировать не нужно

2022-03-15 11:39 UTC, spiderpoul requested changes

2022-03-15 11:39 UTC, spiderpoul commented on src/ex3_js-objects-part1/task-06.js
> +    return String(resultValue);
попробуй упростить алгоритм, как я описал выше, такой проблемы быть не должно

2022-03-15 11:41 UTC, MichaelMindman commented on src/ex3_js-objects-part1/task-06.js
> +          getCheckObject(objectInput[key]);
Я сейчас обратил внимание что ТЕСТы обновились, сейчас идет проверка на 'awf' и гundefined. А ранее была еще проверка с результатом false - наврерное тесты изменились.

2022-03-16 20:06 UTC, MichaelMindman commented on src/ex3_js-objects-part1/task-06.js
> +    return String(resultValue);
Эх... и вчера и сегодня пытался сделать. По простому неполучается, вроде начинаю писать - а в итоге постоянно усложняется код, и в алгоритме на листочке находятся дополнения, что не  учел при анализе. В итоге просто "тону в задаче", и понимаю что не тот вариант решения . 
Наверное сейчас я только понял саму задачу и что нужно сделать для её решения . Но как её сделать и тем более как сделать легко - пока не знаю.

2022-03-26 07:28 UTC, merged